---
layout: post
title: 'Quick Tip: Making Ringtones in iTunes'
date: '2006-12-23T13:30:00.000-05:00'
author: jenny
tags:
- mac
- tip
modified_time: '2006-12-23T13:58:12.103-05:00'
thumbnail: http://bp0.blogger.com/_Gj3xvk4ycVs/RY14NoVvirI/AAAAAAAAADk/_1U77JV2L-U/s72-c/itunes.jpg
blogger_id: tag:blogger.com,1999:blog-5518298822864690168.post-2963145021226578777
blogger_orig_url: https://www.hackaddict.net/2006/12/quick-tip-making-ringtones-in-itunes.html
---

Today I am going to show you guys how to make mp3's into ring tones for your cell phone.  I use this method because it's free and I get to choose exactly what part of the song I want.  For starters you're going an mp3 of the song you want to use, iTunes, and a way to get the song from your computer to your phone (I have a Razr with bluetooth and use that, but you could also use a usb cable).<br /><br />Now that you have everything it's time to load iTunes and being setting it up (This is a tutorial for Mac iTunes, which should be the same for windows with some slight differences on menu locations):<br /><a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://bp0.blogger.com/_Gj3xvk4ycVs/RY14NoVvirI/AAAAAAAAADk/_1U77JV2L-U/s1600-h/itunes.jpg"><img style="margin: 0pt 0pt 10px 10px; float: right; cursor: pointer; width: 221px; height: 265px;" src="http://bp0.blogger.com/_Gj3xvk4ycVs/RY14NoVvirI/AAAAAAAAADk/_1U77JV2L-U/s320/itunes.jpg" alt="" id="BLOGGER_PHOTO_ID_5011794135895476914" border="0" /></a><br />1. Go to the iTunes menu, Preferences..., Advanced, and then click on the importing tab.<br />2. On the "Import Using" select "MP3 encoder" from the drop down menu.<br />3. Next go to the "Setting" drop down menu and select "Custom."<br />4. Change stereo bit rate to 64 kbps and leave everything else the same.  Click ok.<br /><br />You are now done with all the prep work aka the "hard part.  " It's time to select which part of the song you want to be your ring tone and actually make the ring tone.<br /><br />1. Right click on the song you are going to make into a ringer and select "Get Info."<br />2.Go to the options tab and go down to the "Start Time" and "Stop Time" check boxes.  Check both boxes and input the time you want your ringer to start/stop.  Click ok when you're done.<br /><br /><a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://bp0.blogger.com/_Gj3xvk4ycVs/RY16HoVvisI/AAAAAAAAADs/QXxByxt0uCM/s1600-h/song.jpg"><img style="margin: 0px auto 10px; display: block; text-align: center; cursor: pointer; width: 233px; height: 215px;" src="http://bp0.blogger.com/_Gj3xvk4ycVs/RY16HoVvisI/AAAAAAAAADs/QXxByxt0uCM/s320/song.jpg" alt="" id="BLOGGER_PHOTO_ID_5011796231839517378" border="0" /></a><br />3.  Highlight your newly "clipped" song and go up to the advanced tab.  Click "Convert Selection to MP3."  The song will be re-encoded using the start and stop times determined.<br />4. Congratulations, you're done!  Navigate to your iTunes Music folder, locate your song, and transfer it to your phone (via bluetooth or usb).<br />*Remember to go back into iTunes and uncheck your custom start and stop times for the original version of your song.